application:
  name: My Blog

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  servlet:
    context-path: /my-blog